package selenium;

// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import server.models.Customer;
import server.repositories.CustomerRepository;
import server.services.CustomerService;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class RegisterCustomerTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Mock
    CustomerRepository customerRepository;

    @InjectMocks
    private CustomerService cs;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        String os = System.getProperty("os.name").toLowerCase();
        if(os.contains("win"))
            System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
        else if (os.contains("nux")){
            System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver");
        }else if(os.contains("mac")){
            //Rajouter le webdriver mac
        }
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void register() {
        driver.get("http://localhost:4200/register");
        driver.manage().window().setSize(new Dimension(1262, 662));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("golouboff");
        driver.findElement(By.id("firstname")).click();
        driver.findElement(By.id("firstname")).sendKeys("seb");
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("seb@seb.com");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("sdgsdgsdgsdgsdgsdgsd");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector(".form-group")).click();

        Mockito.when(customerRepository.findById("sgolouboff")).thenReturn(Optional.of(new Customer()));
        assertTrue(cs.getById("sgolouboff").isPresent());
    }
}