package selenium;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.junit4.SpringRunner;
import server.repositories.CustomerRepository;
import server.services.CustomerService;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertTrue;

@RunWith(SpringJUnit4ClassRunner.class )
public class RegisterCustomerTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Autowired
    private CustomerRepository cr;

    @Before
    public void setUp() {
        String os = System.getProperty("os.name").toLowerCase();
        if(os.contains("win"))
            System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
        else if (os.contains("nux")){
            System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver");
        }else if(os.contains("mac")){
            //Rajouter le webdriver mac
        }
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void register() {
        driver.get("http://localhost:4200/register");
        driver.manage().window().setSize(new Dimension(1262, 662));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("golouboff");
        driver.findElement(By.id("firstname")).click();
        driver.findElement(By.id("firstname")).sendKeys("seb");
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("seb@seb.com");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("sdgsdgsdgsdgsdgsdgsd");
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.cssSelector(".form-group")).click();

        CustomerService cs = new CustomerService();

        assertTrue(cs.getById("sgolouboff").isPresent());
    }
}