version: '3.8'
services:  
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
     POSTGRES_USER: hackathon
     POSTGRES_PASSWORD: hackathon
     POSTGRES_DB: hackathon
    ports:
     - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: hackathon
    ports:
      - "3254:80"
